# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Random effects fit
#'
#' Fits a random-effects model (with no fixed effect covariates other than the intercept). Operates on any number of traits at once, but treats them as independent.
#'
#' @param yVec vectorized matrix of phenotypes
#' @param kVec vectorized relationship matrix
#' @param repFac factor relating genotypes to replicates
#' @param d number of traits
#' @param Ngen number of genotypes
#' @export
reFit <- function(yVec, kVec, repFac, d, Ngen) {
    .Call(`_GWAlikeMeth_reFit`, yVec, kVec, repFac, d, Ngen)
}

#' GWA with no fixed effect covariates
#'
#' Fits a random-effects model (with no fixed effect covariates other than the intercept) and does GWA on the provided SNPs. Operates on any number of traits at once, but treats them as independent.
#'
#' @param yVec vectorized matrix of phenotypes
#' @param kVec vectorized relationship matrix
#' @param repFac factor relating genotypes to replicates
#' @param snps SNP matrix, SNPs as columns
#' @param d number of traits
#' @param Ngen number of genotypes
#' @export
gwa <- function(yVec, kVec, repFac, snps, d, Ngen) {
    .Call(`_GWAlikeMeth_gwa`, yVec, kVec, repFac, snps, d, Ngen)
}

